apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hwf-chatbot-router-ingress
  namespace: {{ .Values.hwfplatform.routerNamespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /function/stack-channel-router.hwf-chatbot$1$2
spec:
  rules:
  - host: {{ .Values.hwfplatform.hostname }}
    http:
      paths:
        - path: /bot(/|$)(.*)
          pathType: Prefix
          backend:
            service:
              name: gateway
              port:
                number: 8080